---
edxlocal_debian_pkgs:
  - postfix
  - libjpeg-dev

edxlocal_databases:
  - "{{ INSIGHTS_DATABASE_NAME | default(None) }}"
  - "{{ ORA_MYSQL_DB_NAME | default(None) }}"
  - "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}"
  - "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}"
  - "{{ EDX_NOTES_API_MYSQL_DB_NAME | default(None) }}"
  - "{{ PROGRAMS_DEFAULT_DB_NAME | default(None) }}"
  - "{{ ANALYTICS_API_DEFAULT_DB_NAME | default(None) }}"
  - "{{ ANALYTICS_API_REPORTS_DB_NAME | default(None) }}"

edxlocal_database_users:
  - {
      db: "{{ INSIGHTS_DATABASE_NAME | default(None) }}",
      user: "{{ INSIGHTS_DATABASES.default.USER | default(None) }}",
      pass: "{{ INSIGHTS_DATABASES.default.PASSWORD | default(None) }}"
    }
  - {
      db: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}",
      user: "{{ XQUEUE_MYSQL_USER | default(None) }}",
      pass: "{{ XQUEUE_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE_NAME | default(None) }}",
      user: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE.username | default(None) }}",
      pass: "{{ ANALYTICS_PIPELINE_OUTPUT_DATABASE.password | default(None) }}"
    }
  - {
      db: "{{ HIVE_METASTORE_DATABASE_NAME | default(None) }}",
      user: "{{ HIVE_METASTORE_DATABASE.user | default(None) }}",
      pass: "{{ HIVE_METASTORE_DATABASE.password | default(None) }}"
    }
