- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
    CLUSTER_NAME: 'edxapp'
  serial: "{{ serial_count }}"
  roles:
    - aws
    - edxapp
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
    - role: minos
      when: COMMON_ENABLE_MINOS
